### ISSUE TITLE
App text

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/service.allocation.viz#6]
Replace lorem ipsum text with actual app text

**Comment by dpena523** [comment]
[Service Allocation Web Tool Text.docx](https://github.com/Metropolitan-Council/service.allocation.viz/files/6029571/Service.Allocation.Web.Tool.Text.docx)
text for slider tool

**Comment by dpena523** [comment]
[Service Allocation Web Tool Text 2-23-21.docx](https://github.com/Metropolitan-Council/service.allocation.viz/files/6031882/Service.Allocation.Web.Tool.Text.2-23-21.docx)
Updated text for slider tool, same as before but includes ideas for charts on summary tab and the need for a footnote on the scenario summary tab.

**Comment by dpena523** [comment]
Most Up to Date Webtext; now includes new category names
[Service Allocation Web Tool Text 3-2-21.docx](https://github.com/Metropolitan-Council/service.allocation.viz/files/6071973/Service.Allocation.Web.Tool.Text.3-2-21.docx)

**Comment by dpena523** [comment]
Updates for the slider tool

- [x]  Tool Text word doc now has updated text to explain scenario improvements types, ideally would be included in hover over, maybe with question mark next to each improvement type?
- [x] For "What market areas will be served by these improvements?" chart is it possible to have a static Y-axis?
- [x] Fix typo in "Change in Access by Service Type"
- [x] Possible to include Route Service Type descriptions between scenario spectrum and scenario summaries?
- [x] On improvement types, is it possible to change values of Expanded on demand service from "0" to "No" and "1" to "Yes"?
- [x] Updated text for improved service slide, clarifies that percentages in the chart reflect percent of regional total population with access to improved service, to remain consistent with reports on the project.
